services:
  database:
    image: postgres:latest
    container_name: SANCHEZ_DB
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - '5455:5432'

volumes:
  postgres_data:
